In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "../data/processed/ev_sales_feature_engineered.csv",
    parse_dates=["Date"]
)

df.head()

,Date,Year,Month,State,Vehicle_Category,EV_Sales,Quarter,Month_Name,Year_Month,Lag_1,Lag_2,Lag_3,Rolling_3,Rolling_STD_3,MoM_Growth
0,2021-01-01,2021,1,Delhi,Electric 2W,2300,1,January,2021-01,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,2021-02-01,2021,2,Delhi,Electric 2W,2450,1,February,2021-02,2300.0,0.0,0.0,0.000000,0.000000,6.521739
2,2021-03-01,2021,3,Delhi,Electric 2W,2860,1,March,2021-03,2450.0,2300.0,0.0,2536.666667,289.885035,16.734694
3,2021-04-01,2021,4,Delhi,Electric 2W,2700,2,April,2021-04,2860.0,2450.0,2300.0,2670.000000,206.639783,-5.594406
4,2021-05-01,2021,5,Delhi,Electric 2W,3020,2,May,2021-05,2700.0,2860.0,2450.0,2860.000000,160.000000,11.851852

In [3]:
df.columns

Index(['Date', 'Year', 'Month', 'State', 'Vehicle_Category', 'EV_Sales',
       'Quarter', 'Month_Name', 'Year_Month', 'Lag_1', 'Lag_2', 'Lag_3',
       'Rolling_3', 'Rolling_STD_3', 'MoM_Growth'],
      dtype='object')

In [4]:
df = pd.get_dummies(
    df,
    columns=["State", "Vehicle_Category"],
    drop_first=True
)

In [5]:
df.head()

,Date,Year,Month,EV_Sales,Quarter,Month_Name,Year_Month,Lag_1,Lag_2,Lag_3,Rolling_3,Rolling_STD_3,MoM_Growth,State_Karnataka,State_Maharashtra,State_Uttar Pradesh,Vehicle_Category_Electric 3W,Vehicle_Category_Electric 4W
0,2021-01-01,2021,1,2300,1,January,2021-01,0.0,0.0,0.0,0.000000,0.000000,0.000000,False,False,False,False,False
1,2021-02-01,2021,2,2450,1,February,2021-02,2300.0,0.0,0.0,0.000000,0.000000,6.521739,False,False,False,False,False
2,2021-03-01,2021,3,2860,1,March,2021-03,2450.0,2300.0,0.0,2536.666667,289.885035,16.734694,False,False,False,False,False
3,2021-04-01,2021,4,2700,2,April,2021-04,2860.0,2450.0,2300.0,2670.000000,206.639783,-5.594406,False,False,False,False,False
4,2021-05-01,2021,5,3020,2,May,2021-05,2700.0,2860.0,2450.0,2860.000000,160.000000,11.851852,False,False,False,False,False

In [6]:
y = df["EV_Sales"]

In [7]:
X = df.drop(
    columns=[
        "Date",
        "EV_Sales",
        "Month_Name",
        "Year_Month"
    ]
)

In [8]:
print(X.shape)
print(y.shape)

(288, 14)
(288,)

In [9]:
split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

In [10]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(230, 14)
(58, 14)
(230,)
(58,)

In [11]:
import joblib

In [12]:
joblib.dump(X_train, "../models/X_train.pkl")
joblib.dump(X_test, "../models/X_test.pkl")

joblib.dump(y_train, "../models/y_train.pkl")
joblib.dump(y_test, "../models/y_test.pkl")

['../models/y_test.pkl']